# Generated by Django 5.1.2 on 2025-05-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_event_id_event_event_id_group_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
    ]
