# Generated by Django 5.2.1 on 2025-05-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_post_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
    ]
